export const PARSE_RANDOM = {
  BOOL: ['TRUE','FALSE'],
  DIRECTION: ['NORTH','SOUTH','EAST','WEST'],
  SURROUNDING: ['NORTH','SOUTH','EAST','WEST','NORTHEAST','NORTHWEST','SOUTHEAST','SOUTHWEST','CENTER'],
}