const GRID_HEIGHT = 13
const GRID_WIDTH = 13

export const RENDER_MAZE_AS = {
  PASSAGE: 'RENDER_MAZE_AS.PASSAGE',
  WALLED: 'RENDER_MAZE_AS.WALLED'
}

export const SETTINGS = {
  GRID_HEIGHT,
  GRID_WIDTH,
  RENDER_MAZE_AS,
}
